---
exporter:
  listenAddress: 127.0.0.1:9103
nodes:
  - url: https://localhost
    username: doesnt
    password: matter
    labels:
      env: production
    caCertFile: /path/to/nifi-cert.pem
    clientCertFile: /path/to/crt.pem
    clientKeyFile: /path/to/key.pem